/**
 * Devpost gallery assets, all reproducible:
 *   pnpm gallery                 → docs/gallery/01-thumbnail.png (2400×1600, 3:2), 02-architecture.png, and board
 *                                  screenshots from BASE (default https://outfitter.skulora.com)
 *   MISSION=m_xxx pnpm gallery   → reuse an existing mission instead of driving the built-in agent (~2 min, OpenAI spend)
 *   pnpm gallery --static        → only the two rendered images, no browser session against BASE
 * Rendered images use the same Mark as the app (public/logo.svg); numbers come from the live board, never typed.
 */
import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { chromium, type Page } from "playwright-core";

const BASE = process.env.BASE ?? "https://outfitter.skulora.com";
const OUT = "docs/gallery";
const STATIC = process.argv.includes("--static");
mkdirSync(OUT, { recursive: true });

async function main() {
  const browser = await chromium.launch({ channel: "chrome", headless: true });
  const markSrc = "data:image/svg+xml;base64," + readFileSync("public/logo.svg").toString("base64");

  async function renderTemplate(name: string, out: string) {
    const page = await browser.newPage({ viewport: { width: 2400, height: 1600 }, deviceScaleFactor: 1 });
    await page.setContent(readFileSync(`scripts/gallery/${name}.html`, "utf8").replaceAll("MARK_SRC", markSrc), { waitUntil: "networkidle" });
    await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: `${OUT}/${out}`, type: "png" });
    await page.close();
  }

  async function shot(page: Page, out: string, opts: { fullPage?: boolean; clip?: { x: number; y: number; width: number; height: number } } = {}) {
    await page.screenshot({ path: `${OUT}/${out}`, type: "png", ...opts });
  }

  await renderTemplate("thumbnail", "01-thumbnail.png");
  await renderTemplate("architecture", "02-architecture.png");

  if (!STATIC) {
    // 3:2 board captures at 2× for crisp gallery rendering.
    const ctx = await browser.newContext({ viewport: { width: 1200, height: 800 }, deviceScaleFactor: 2, colorScheme: "dark" });
    const page = await ctx.newPage();
    let mission = process.env.MISSION;
    if (mission) {
      await page.goto(`${BASE}/?m=${mission}`);
    } else {
      await page.goto(BASE + "/");
      await page.fill("input[placeholder^='Tell the agent']", "Outfit me for a 3-day desert backpacking trip, budget $600, I already own a stove. Pick something for every slot, then prepare the checkout carts.");
      await page.click("button:has-text('Send')");
      await page.waitForFunction(() => !document.querySelector("form button[disabled]"), null, { timeout: 240000 });
      mission = (await page.evaluate(() => localStorage.getItem("skulora.missionId"))) ?? undefined;
      console.log("mission", mission);
    }
    await page.waitForSelector("text=selected across", { timeout: 20000 });
    await page.waitForTimeout(1500);
    await page.evaluate(() => window.scrollTo(0, 0));
    await shot(page, "03-board-kit.png");
    // Co-driving: lock the first pick, reject the second, then ask the agent to re-plan so the panel shows the mission_delta arriving.
    const lock = page.locator("button:has-text('lock')").first();
    if (await lock.count()) await lock.click();
    page.once("dialog", (d) => void d.accept("too heavy for desert"));
    const reject = page.locator("button:has-text('reject')").nth(1);
    if (await reject.count()) await reject.click();
    await page.waitForTimeout(1500);
    await shot(page, "04-board-codriving.png");
    await page.fill("input[placeholder^='Tell the agent']", "I changed the board — re-plan within budget.");
    await page.click("button:has-text('Send')");
    await page.waitForFunction(() => !document.querySelector("form button[disabled]"), null, { timeout: 240000 });
    await page.waitForTimeout(1500);
    await page.evaluate(() => window.scrollTo(0, 0));
    await shot(page, "05-replan.png");
    const checkout = page.locator("text=Checkout — one cart per merchant");
    if (await checkout.count()) {
      await checkout.scrollIntoViewIfNeeded();
      await page.evaluate(() => window.scrollBy(0, -24));
      await page.waitForTimeout(500);
      await shot(page, "06-checkout.png");
    } else console.warn("no checkout section on the board — ask the agent to prepare_checkout, then re-run with MISSION=" + mission);
    await ctx.close();
  }
  await browser.close();

  for (const f of ["01-thumbnail.png", "02-architecture.png"]) console.log(f, Math.round(statSync(`${OUT}/${f}`).size / 1024) + " KB");
  writeFileSync(`${OUT}/README.md`, `# Devpost gallery\n\nGenerated by \`pnpm gallery\` (see scripts/gallery.ts). 01 is the 3:2 thumbnail; 03–06 are live captures of ${BASE} (the WebMCP pill reads "unsupported" because headless Chrome has no WebMCP flag — re-shoot 03/04 in flagged Chrome or ChatGPT for the gallery if you want the pill green).\n`);

}

void main();
